import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";


export const metadata: Metadata = {
  title: "DnG Projects",
  description: "Generated by OlivierBurle for a Futur Job",
};
const openSans = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
